### ISSUE TITLE
Discussion: Having a max line length rule

### ISSUE THREAD

**Issue by abhishalya** [30-seconds/30-seconds-of-julia#25]
I strongly recommend having a rule on maximum length of a line. It makes things easier to edit and overall files look much cleaner.

@Chalarangelo

**Comment by Chalarangelo** [comment]
Format will follow the existing guidelines of content repos. Max line length should only be applied to the code in snippets - not description and explanation, as this is handled by other tools afterwards. However, description and explanation should be written one sentence per line to keep commit history as clean as possible.
