### ISSUE TITLE
DO NOT OPEN ISSUES FOR SNIPPETS YOU ARE GOING TO PR

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-of-julia#26]
Hey all, hope the all caps title got your attention. There is no need to open an issue before PRing a new snippet. Just open your PR with the proposed code and explain anything you need in that. Thanks!

**Comment by logankilpatrick** [comment]
Hey, I updated this on my end so there should no longer be any issues. Students were opening issues in order to claim the specific exercise in order to not overlap on work.
