### ISSUE TITLE
Snippets already added in 30-seconds-Julia (mostly from 30-seconds-python)

### ISSUE THREAD

**Issue by PseudoCodeNerd** [30-seconds/30-seconds-of-julia#35]
## Snippets Added 
3 Tasks in The Julia Programming Language (Google Code-In) require students to add julia snippets of varying difficulty to 30-seconds repository.
This issue is to keep track of all the snippets that participants have contributed. This is to ensure that no student starts making a snippet that has already been added.

All Available Python [Snippets](https://github.com/30-seconds/30-seconds-of-python/tree/master/snippets)
Snippets added to Julia below,
<hr>

- [x] average.md
- [x] all_equal.md
- [x] capitalize.md
- [x] palindrome.md
- [x] is_anagram.md
- [x] frequency.md
- [x] has_duplicates.md
- [x] bifurcate.md
- [x] bifurcate_by.md
- [x] geometric_mean.md
- [x] harmonic_mean.md
- [x] camelCase.md
- [x] fibonacci.md
- [x] digitize.md
- [x] head.md
- [x] is_even.md
- [x] is_odd.md
- [x] intersection_by.md
- [x] longest.md
- [x] root_mean_square.md
- [x] luhn.md
- [x] lcm.md
- [x] pullAtValue.md
- [x] pullAtIndex.md
- [x] pretty_bytes.md

**Comment by logankilpatrick** [comment]
This is what a WIP pull request is supposed to accomplish. Also, you can find something that looks interesting to you to convert to Julia and then check if it's in the repo already. No need to make an issue here. Thanks for taking the initiative on this @PseudoCodeNerd
